# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/karchive': '@stable'
    'frameworks/kcompletion': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kconfigwidgets': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/knotifications': '@stable'
    'frameworks/kxmlgui': '@stable'
